### ISSUE TITLE
have

### ISSUE THREAD

**Issue by alexwq100** [hdjang/mmdetection-hdjang#3]
hi @hdjang ， have you reproduced the performance reported in the paper? thks

**Comment by hdjang** [comment]
Hi, @alexwq100 

Yeah, I checked my implementation shows similar performance achievement as the paper as shown in the benchmark section of README. However, I couldn't check the performance aspect under the same training condition (i.e., same input-size, learning-rate scheduling) due to my limited constraints. You can check it. It would be really appreciated if you confirm that and share the result! :)
